In [21]:
import numpy as np

In [22]:
class NeuralNetwork:
    def __init__(self, x, y):
        # Вектор признаков X
        self.input = x
        # смещение b1
        self.b1 = 1
        # смещение и2
        self.b2 = 1
        # вектор вестов
        self.weights1 = np.array([[0.1, 0.3],
                                 [0.2, 0.4]])
        
        self.weights2 = np.array([[0.5], 
                                 [0.6]])
        
        self.y = y
        self.output = np.zeros(self.y.shape)
        
    # Сигмоида
    def sigmoid(self, x):
        return 1.0/(1 + np.exp(-x))
    
    # ReLU
    def relu(self, x):
        return x * (x > 0)
    
    def feedforward(self):
        self.layer1 = self.sigmoid(np.dot(self.input, self.weights1)+self.b1)
        self.output = self.relu(np.dot(self.layer1, self.weights2)+self.b2)

![title](./conspect/1.png)

In [3]:
X = np.array([2,3])
y = np.array([2])

In [4]:
np.array([[0.1, 0.3],[0.2, 0.4]])

array([[0.1, 0.3],
       [0.2, 0.4]])

In [5]:
np.dot(X, np.array([[0.1, 0.3],[0.2, 0.4]]))+1

array([1.8, 2.8])

In [6]:
nn = NeuralNetwork(x = X, y = y)
nn.feedforward()

In [7]:
print(f'layer1 = {nn.layer1}\n')
# Ответ на обновленных весах
print(f'Output = {nn.output}\n')
# Ошибка
print(f'Error = {1/len(X)*(y - nn.output)**2}\n')

layer1 = [0.85814894 0.94267582]

Output = [1.99467996]

Error = [1.41514021e-05]



![title](./conspect/2.png)

In [8]:
# Дальше идет пример реализации с добавлением обратного распрастранения ошибки

![title](./conspect/3.png)

In [9]:
class NeuralNetwork:
    def __init__(self, x, y, learning_rate):
        # Вектор признаков X
        self.input = x
        # смещение b1
        self.b1 = 1
        # смещение и2
        self.b2 = 1
        # вектор вестов
        self.weights1 = np.array([[0.1, 0.3],
                                 [0.2, 0.4]])
        
        self.weights2 = np.array([[0.5], 
                                 [0.6]])
        
        self.y = y
        self.output = np.zeros(self.y.shape)
        # скорость обучения
        self.learning_rate = learning_rate
        
    # Сигмоида
    def sigmoid(self, x):
        return 1.0/(1 + np.exp(-x))
    
    # Производная сигмоиды
    def sigmoid_derivative(self, x):
        return x * (1.0 - x)
    
    # ReLU
    def relu(self, x):
        return x * (x > 0)
    
    # Производная ReLU
    def relu_derivative(self, x):
        return (x >= 0).astype(float)
    
    # Функция потерь
    def loss(self, y, output):
        return 1/2*(y-output)**2
    
    # Производная функции потерь
    def loss_derivative(self, y, output):
        return y - output
    
    # Прямое распространение ошибки
    def feedforward(self):
        self.layer1 = self.sigmoid(np.dot(self.input, self.weights1)+self.b1)
        self.output = self.relu(np.dot(self.layer1, self.weights2)+self.b2)
        self.error = self.loss(self.y, self.output)
        
        
    # Обратное распространение ошибки
    def backpropagation(self):
        # Первое что необходимо найти первый шаг, без входного слоя. Это первый шаг когда мы
        # начинаем шагать в обратную сторону
        """
        ВЫХОДНОЙ СЛОЙ - предварительное вычисление
        Вычисляем первую часть для w11(w21) -> ((target_o1 - outo_1)*outo_1*(1-outo_1))
        """
        Q_w2 = self.learning_rate * self.loss_derivative(self.y, self.output) * self.relu_derivative(self.output)
        
        
        # дальше выходы из скрытых слоев умножаем на вектор этих скрытых слоев и получаем
        # то dQ по dw на которые нужно изменить веса на второй ступени
        """
        ВЫХОДНОЙ СЛОЙ
        Есть массив первичных вычислений Q_w2
        для w11_2 --> Q_w2*outh_1
        для w21_2 --> Q_w2*outh_2
        Получаем массив --> [w11, w21]
        """
        dQ_dw2 = Q_w2 * swlf.layer1.reshape(-1, 1)
        
        
        """
        СКРЫТЫЙ СЛОЙ - предварительное вычисление
        Для w11(w21) --> (target_o1-outo_1)*relu᾿*w_11_2*outh_1*(1-outo_1)*input_1
        Для w12(w22) --> (target_o1-outo_1)*relu᾿*w_21_2*outh_2*(1-outo_2)*input_2

        """
        dQ_dw1_1 = self.learning_rate * (self.loss_derivative(self.y, self.output) * \
                                         self.relu_derivative(self.output)) @ \
                                         self.weights2.T * \
                                         self.sigmoid_derivative(self.layer1)
        
        dQ_dw1 = np.matrix(dQ_dw1_1).T @ np.matrix(self.input)
        
        
        # Обновляем веса
        self.weights1 += dQ_dw1
        self.weights2 += dQ_dw2

In [11]:
nn = NeuralNetwork(x=X, y=y, learning_rate=0.1)

In [ ]:
# TODO вставь картинки из видео

In [13]:
for i in range(2):
    nn.feedforward()
    nn.backpropagation
    print(f'==============EPOCH: {i}========================')
    print(f'weights1 =\n {nn.weights1} \n')
    print(f'weights2 =\n {nn.weights2} \n')
    
    print(f'hidden layer = {nn.layer1} \n')
    
    # Ответ на обновленных весах
    print(f'Output {i} = {nn.output}')
    print(f'Error {i} = {nn.error} \n')

==============EPOCH: 0========================
weights1 =
 [[0.1 0.3]
 [0.2 0.4]] 

weights2 =
 [[0.5]
 [0.6]] 

hidden layer = [0.85814894 0.94267582] 

Output 0 = [1.99467996]
Error 0 = [1.41514021e-05] 

==============EPOCH: 1========================
weights1 =
 [[0.1 0.3]
 [0.2 0.4]] 

weights2 =
 [[0.5]
 [0.6]] 

hidden layer = [0.85814894 0.94267582] 

Output 1 = [1.99467996]
Error 1 = [1.41514021e-05] 

